namespace test.lox;
using test.lox.Fraction;

try{
    val frac = Fraction(3, 0);
    println("Try statement executed successfully.");
}
catch(Exception e){ 
    println("Caught exception with message: " + e.message);
}
